--SELECT*FROM EMPLOYEES WHERE DEPARTMENT_ID =90
--SELECT FIRST_NAME LAST_NAME FROM EMPLOYEES WHERE FIRST_NAME LIKE 'B%'
--SELECT *FROM EMPLOYEES WHERE SALARY > '2000' 
--SELECT *FROM EMPLOYEES WHERE SALARY >= '2000' AND EMAIL LIKE 'C%'
--SELECT *FROM EMPLOYEES WHERE SALARY > '2000' OR EMAIL LIKE 'C%'


